// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqjqMjKGgfwV8-osKn-3yoFh57ah8b8wQ',
    appId: '1:861546983434:web:0bd29d4d9efd7775856ff3',
    messagingSenderId: '861546983434',
    projectId: 'dots-b3559',
    authDomain: 'dots-b3559.firebaseapp.com',
    storageBucket: 'dots-b3559.appspot.com',
    measurementId: 'G-R8P4SCYLY7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ629zCBF4CJWA7FfUMpQIVi5xq97GJlo',
    appId: '1:861546983434:android:1fc5e1eb57032a95856ff3',
    messagingSenderId: '861546983434',
    projectId: 'dots-b3559',
    storageBucket: 'dots-b3559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBR2d8qPJ6SfnZPdt0T4hh6kdMAeyM9ufA',
    appId: '1:861546983434:ios:c179d0631eece98d856ff3',
    messagingSenderId: '861546983434',
    projectId: 'dots-b3559',
    storageBucket: 'dots-b3559.appspot.com',
    androidClientId: '861546983434-m1jvqtobj0ms99m662ch3t0g9leg6gbh.apps.googleusercontent.com',
    iosClientId: '861546983434-jedjg0rbvuaqpd4lhqs4gvegiems6ls8.apps.googleusercontent.com',
    iosBundleId: 'com.bataudev.play.dots',
  );

}